# Generated by Django 3.1.4 on 2020-12-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_image', models.ImageField(upload_to='images/')),
                ('job_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
